# smoke-test-config.yaml (with pattern strategy)
apiVersion: copa.sh/v1alpha1
kind: PatchConfig
metadata:
  description: "Smoke test config including pattern-based tag discovery."

images:
  # Example 1: Test the 'latest' strategy (Kept from previous test)
  - name: "alpine-latest"
    image: "docker.io/library/alpine"
    tags:
      strategy: "latest"
    platforms: ["linux/amd64"] # Keep this filter for now

  # Example 2: Test the 'list' strategy (Kept from previous test)
  - name: "ubuntu-lts"
    image: "docker.io/library/ubuntu"
    tags:
      strategy: "list"
      list: ["22.04"] # Let's reduce this to one to speed up the test
    platforms: ["linux/amd64"] # Keep this filter

  # =================================================================
  # Example 3: NEW - Test the 'pattern' strategy for nginx
  # =================================================================
  - name: "nginx-mainline"
    image: "docker.io/library/nginx"
    tags:
      strategy: "pattern"
      # This pattern will match tags like 1.25.3, 1.24.0, etc.,
      # but will not match tags like "latest" or "stable-perl".
      pattern: "^1\\.2[4-5]\\.[0-9]+$"
      
      # We will get the 2 most recent tags that match the pattern.
      maxTags: 2
      
      # Let's imagine we know a specific version has issues and we want to skip it.
      exclude: ["1.25.2"]
    platforms: ["linux/amd64"] # Filter to our architecture
